"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {HeritageMap} from "./HeritageMap";
type Item={id:string;title:string;kind:string;address:string;place:string;type:"Gebouwd"|"Archeologisch";period:string;description:string;lat:number;lng:number};
const ITEMS:Item[]=[
{id:"527668",title:"Rietveld SchrÃ¶derhuis",kind:"Woonhuis",address:"Prins Hendriklaan 50",place:"Utrecht",type:"Gebouwd",period:"1924",description:"Experimenteel woonhuis van Gerrit Rietveld en een sleutelwerk van De Stijl.",lat:52.0856,lng:5.1475},
{id:"36046",title:"Domtoren",kind:"Kerktoren",address:"Domplein 21",place:"Utrecht",type:"Gebouwd",period:"1254â€“1517",description:"Vrijstaande gotische toren en herkenningspunt van de historische binnenstad.",lat:52.0907,lng:5.1214},
{id:"38755",title:"Kasteel de Haar",kind:"Kasteel",address:"Kasteellaan 1",place:"Haarzuilens",type:"Gebouwd",period:"1892â€“1912",description:"Monumentaal kasteelcomplex met tuinen en park, gerestaureerd door Pierre Cuypers.",lat:52.1214,lng:4.9867},
{id:"531052",title:"Castellum Hoge Woerd",kind:"Romeins castellum",address:"Hoge Woerdplein 1",place:"De Meern",type:"Archeologisch",period:"Romeinse tijd",description:"Archeologisch terrein met resten van een Romeins grensfort.",lat:52.0835,lng:5.0018},
{id:"531034",title:"Fort bij Rijnauwen",kind:"Fort",address:"Vossegatsedijk 5",place:"Bunnik",type:"Gebouwd",period:"1868â€“1871",description:"Groot fort van de Nieuwe Hollandse Waterlinie bij Bunnik.",lat:52.0845,lng:5.1772}];
export default function Home(){const[query,setQuery]=useState("");const[active,setActive]=useState("");const[type,setType]=useState("Alle");const[view,setView]=useState<"list"|"map">("list");const[selected,setSelected]=useState<Item|null>(null);const[filters,setFilters]=useState(false);
useEffect(()=>{const p=new URLSearchParams(location.search),q=p.get("q")||"";setQuery(q);setActive(q);setType(p.get("type")||"Alle");setView(p.get("view")==="map"?"map":"list")},[]);
useEffect(()=>{const p=new URLSearchParams();if(active)p.set("q",active);if(type!=="Alle")p.set("type",type);if(view==="map")p.set("view","map");history.replaceState({},"",p.toString()?"?"+p:location.pathname)},[active,type,view]);
const choose=useCallback((item:Item)=>setSelected(item),[]);
const results=useMemo(()=>{const q=active.toLowerCase();return ITEMS.filter(i=>(type==="Alle"||i.type===type)&&(!q||(i.title+" "+i.kind+" "+i.address+" "+i.place+" "+i.id).toLowerCase().includes(q)))},[active,type]);
return <main><div className="govbar"><img src="/logo-rce.gif" alt="Rijksdienst voor het Cultureel Erfgoed, Ministerie van Onderwijs, Cultuur en Wetenschap"/></div><header><a className="brand" href="#"><b>D</b><span><strong>Doorzoeker</strong><small>Cultureel erfgoed ontdekken</small></span></a><p><i/>Prototype met voorbeelddata <a href="https://linkeddata.cultureelerfgoed.nl/" target="_blank">Over de bronnen</a></p></header>
<section className="hero"><small>ZOEK DOOR MONUMENTEN, PLAATSEN EN VERHALEN</small><h1>Wat wil je ontdekken?</h1><form onSubmit={e=>{e.preventDefault();setActive(query);setSelected(null)}}><span>âŒ•</span><label className="sr" htmlFor="q">Zoeken</label><input id="q" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Bijvoorbeeld Domtoren, Utrecht of 36046"/>{query&&<button type="button" className="clear" onClick={()=>setQuery("")}>Ã—</button>}<button>Zoeken</button></form><nav>Probeer: {["Utrecht","Kasteel","Romeins"].map(t=><button key={t} onClick={()=>{setQuery(t);setActive(t)}}>{t}</button>)}</nav></section>
<section className="work"><aside className={filters?"show":""}><div className="aside-title"><div><small>VERFIJN</small><h2>Filters</h2></div><button onClick={()=>setFilters(false)}>Ã—</button></div><fieldset><legend>Soort monument</legend>{["Alle","Gebouwd","Archeologisch"].map(t=><label key={t}><input type="radio" checked={type===t} onChange={()=>setType(t)}/><span>{t==="Alle"?"Alle monumenten":t}</span><em>{t==="Alle"?ITEMS.length:ITEMS.filter(i=>i.type===t).length}</em></label>)}</fieldset><fieldset><legend>Provincie</legend><label><input type="checkbox" defaultChecked/><span>Utrecht</span><em>5</em></label></fieldset><fieldset><legend>Status</legend><label><input type="checkbox" defaultChecked/><span>Rijksmonument</span><em>5</em></label></fieldset><button className="reset" onClick={()=>{setType("Alle");setActive("");setQuery("")}}>Wis alle filters</button></aside>
<div className="results"><div className="toolbar"><div><small>RIJKSMONUMENTEN</small><h2>{results.length} {results.length===1?"resultaat":"resultaten"}{active?" voor â€œ"+active+"â€":""}</h2></div><div><button className="mobile-filter" onClick={()=>setFilters(true)}>â‰¡ Filters</button><span className="switch"><button className={view==="list"?"on":""} onClick={()=>setView("list")}>â˜·</button><button className={view==="map"?"on":""} onClick={()=>setView("map")}>âŒ–</button></span></div></div>
{results.length===0?<div className="empty"><b>0</b><h3>Geen monumenten gevonden</h3><p>Probeer een plaats, adres, functie of monumentnummer.</p><button onClick={()=>{setActive("");setQuery("");setType("Alle")}}>Toon alle monumenten</button></div>:view==="list"?<div className="cards">{results.map(i=><article key={i.id}><div className={i.type==="Archeologisch"?"tile sand":"tile"}><b>{i.type==="Archeologisch"?"A":"M"}</b><small>{i.type}</small></div><div className="copy"><small>{i.kind}<code>RM {i.id}</code></small><h3>{i.title}</h3><p className="address">â€¢ {i.address}, {i.place}</p><p>{i.description}</p><span>{i.kind}</span><span>{i.period}</span></div><button className="open" onClick={()=>setSelected(i)}>â†’</button></article>)}</div>:<HeritageMap items={results} onSelect={choose}/>}</div></section>
{selected&&<div className="backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="detail"><button className="x" onClick={()=>setSelected(null)}>Ã—</button><div className={selected.type==="Archeologisch"?"detail-head sand":"detail-head"}><b>{selected.type==="Archeologisch"?"A":"M"}</b><small>{selected.type} erfgoed</small></div><div className="detail-copy"><small>RIJKSMONUMENT {selected.id}</small><h2>{selected.title}</h2><p>{selected.address}<br/>{selected.place}, Utrecht</p><hr/><p>{selected.description}</p><dl><div><dt>Status</dt><dd>Rijksmonument</dd></div><div><dt>Functie</dt><dd>{selected.kind}</dd></div><div><dt>Datering</dt><dd>{selected.period}</dd></div><div><dt>Monumentaard</dt><dd>{selected.type}</dd></div></dl><a href={"https://linkeddata.cultureelerfgoed.nl/cho-kennis/id/rijksmonument/"+selected.id} target="_blank">Bekijk de bron bij RCE <b>â†’</b></a><blockquote>Voorbeeldrecord. In de volgende stap laden we dit live uit RCE Linked Data.</blockquote></div></aside></div>}</main>}
